name: Node.js package audit

on: push

jobs:
  package-audit:
    strategy:
      matrix:
        node-version:
          - 22
    runs-on: ubuntu-24.04
    name: Node.js package audit
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Audit npm packages
        run: cd export-server && npm audit
